### ISSUE TITLE
Implementation and validation of login github.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#393]
Se necesita implementar el inicio de sesión de github en fermat-org, esto se requiere para la versión 3 de fermat-org.

Tareas que se necesitan realizar:

- [x] Añadir botón de inicio de sesión. (Discutir con @Miguelcldn para su posición final).
- [x] Validar datos. (Conversar sobre este tema con el equipo de servidor y crear los casos necesarios para su realización).
- [x] Mostrar perfil básico en fermat-org(usuario) y añadir botón de cierre de sesión.
- [x] Encontrar la forma de mantener iniciada sesión una vez cerrada la página.
- [x] Añadir documentacion del codigo.

necesario para #377

**Comment by Miguelcldn** [comment]
La clase `buttonsManager` puede encargarse de siempre mostrar el botón de iniciar sesión arriba a la derecha puesto que es un botón que siempre estará disponible sin importar la vista. Igualmente el botón de cerrar sesión y el nombre de usuario conectado (no necesariamente tiene que estar la foto).

La autorización de github a dev.fermat.org la controla github, no es necesario mantener nosotros la sesión, una vez que el usuario le de a "Iniciar sesión" en nuestra página, si github tiene la sesión iniciada inmediatamente estará logeado apenas presione el boton. Quien se ha encargado de la autorización de github es @campol, probablemente este issue sea asignado a él una vez termine sus issues relacionados

**Comment by emmanuelcolina** [comment]
- [ ] Hacer que los datos(perfil basico) de inicio de sesión de un usuario floten por todas las vistas.
- [ ] La variable isLogin hacerla solamente publica en su clase.
- [ ] Renombrar la Clase Login.
- [ ] Hacer que una persona edite la tabla si y solo si, tiene su sesión abierta en github.
- [ ] Al hacer click en el botón "Logout" la variable isLogin = false, y el boton vuelva a "Login"
