### ISSUE TITLE
Create modal for Fields fermat-edit.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#435]
Se necesita añadir los campos de descripción, directorio y todos los autores del componente, algunos de estos nuevos campos son demasiados largo o necesitan un espacio adicional porque se necesitan añadir varios autores de una lista. La solución para este problema de espacio es crear un modal para mostrar estos campos.

necesario para #377.

**Comment by DarilRodriguez** [comment]
![img_20022016_001450](https://cloud.githubusercontent.com/assets/7703770/13237501/6c0889ae-d9ab-11e5-8f9f-002a17354112.png)

**Comment by Miguelcldn** [comment]
Bien, pero se ve muy _alien_ con respecto al resto del diseño de la página, usa los colores de fermat

**Comment by ricardo460** [comment]
Realizar estas mejoras : 

- [ ] No se obtienen los valores de scope, role y %, en fillTable();
- [ ] No se muestra la información de scope, role y %, en el modal al editar un componente.
- [ ] Al parecer un mismo desarrollador puede aparecer varias veces pero con diferentes roles, Cambiar restricción para cumplir con esta tarea.
- [ ] Cambiar colores por los de fermat.
