### ISSUE TITLE
Create function for the complete information of a component.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#436]
hay que crear una función para obtener todos los datos que faltan de un componente como:

* Descripción.
* Autores y su información.
* life cycle y su información.

Añadir también el id del componente para su modificacion o eliminacion.

Necesario para #377.

**Comment by Miguelcldn** [comment]
Sin Life Cycle por ahora, un solo autor con 100% de responsabilidad. Solo la descripción, un cuadro de texto en el formulario.
