### ISSUE TITLE
Somehow create a .png or .jpg of the table view

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#440]
For light showing purpose, set available that the renderer takes a (big) picture of the table view, rendering the table view in a .jpg or .png file so anyone can see the table even if (s)he has not a powerful PC.

Requested by @gustl-arg

**Comment by gustl-arg** [comment]
@Miguelcldn any good willed member that could do this ?

**Comment by Miguelcldn** [comment]
Since we finished one of our nightmares, we can now!

**Comment by Miguelcldn** [comment]
Concluded that the alternative to low-spec users can use is to enter to dev.fermat.org/#canvas , with this URL the rendering will be in a HTML Canvas, and thus reducing the resources needs in terms of GPU at expenses of a lower graphic quality and more RAM requirement (up to the browser).
