### ISSUE TITLE
Plan the estimated time for workflows

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#441]
Pon en el comentario de cierre la planificación o cronograma

**Comment by emmanuelcolina** [comment]
- [ ] Crear una interfaz flotante en la vista WorkFlow.
       * Titulo del Header Flow 
       * Sub titulo del Header Flow
       * Cantidad de pasos (ID)
           * Descripción
           * Tipo de llamada
       * Tipo Plataforma
       * Desarrollador 
- [ ] Organizar algunos de los componentes de WorkFlow.
- [ ] Programar: Editar eliminar y crear  WorkFlow.
      - [ ] Dibujar WorkFlow
      - [ ] Posicionar WorkFlow


Se estima entre una semana y media o dos la culminación.

**Comment by Miguelcldn** [comment]
Next: #460

**Comment by ricardo460** [comment]
Se moverá toda esta estructura de trabajo en sus respectivos issues. @emmanuelcolina @Miguelcldn

**Comment by ricardo460** [comment]
Tiempo estimado para el dia martes 22/03/2016.
