### ISSUE TITLE
API Server is sending wrong process ID and empty avatar_url

### ISSUE THREAD

**Issue by IsaTab** [Fermat-ORG/fermat-org#442]
- There's some missing data and avatars aren't loaded in Architecture.
- The ID setup changed in the workflows definition, causing all but the test case to be undrawable since the IDs that indicate steps within a workflow don't match the IDs used to define those steps.

**Comment by Miguelcldn** [comment]
@IsaTab please, provide the name of one of the workflows with the problem described, and the same for the tiles with missing avatar in order to diagnose

**Comment by IsaTab** [comment]
- Workflow: Refuse Payment Request from Intra user

{"platfrm":"CCP","name":"Refuse Payment Request from Intra user","desc":"A Wallet's Intra User refuse a payment request sent by another actor.","prev":"List Payment Request","next":null,"steps":[{"id":49,"title":"Select payment request record to refuse","desc":"The actor selects a payment request from the list and press deny button.","type":"start","next":[{"type":"direct call","id":"1"}]},{"id":50,"title":"Route request to payment request plugin","desc":"The module routes this payment request refuse to the Crypto Payment Request Plugin to reach the selected intra user.","type":"activity","next":[{"type":"direct call","id":"2"}],"name":"crypto wallet","layer":"wallet module","platfrm":"CCP"},{"id":51,"title":"Route refuse to network service","desc":"The module routes this refuse to the network service to reach the selected intra user.","type":"activity","next":[{"type":"direct call","id":"3"}]},{"id":52,"title":"Call the intra user to deliver the refuse","desc":"The network service places a call to the intra user and then it delivers the refuse via the Fermat network.","type":"activity","next":[{"type":"direct call","id":"4"}],"name":"crypto payment request","layer":"network service","platfrm":"CCP"},{"id":53,"title":"Transport request","desc":"The payment request is transported through the communication layer and one of the available channels.","type":"communication","next":[{"type":"fermat message","id":"5"}]},{"id":54,"title":"Receive the payment request","desc":"The network service receives the refuse and informs that to Request Crypto Payment Plugin.","type":"activity","next":[{"type":"event","id":"6"}],"name":"crypto payment request","layer":"network service","platfrm":"CCP"},{"id":55,"title":"Update the request status","desc":"The payment request is update with the status deny.","type":"activity","next":[{"type":"direct call","id":"7"}],"name":"crypto payment","layer":"request","platfrm":"CCP"},{"id":56,"title":"Return payment request send list","desc":"The module returns the payement request send list.","type":"activity","next":[{"type":"direct call","id":"8"}],"name":"crypto wallet","layer":"wallet module","platfrm":"CCP"},{"id":57,"title":"List Send Payment Request","desc":"The wallet's user go to Payment Request menu and list payment request send, and show this status.","type":"end","next":[]}],"upd_at":"56c500337d20701f4141eca8","_id":"56c500337d20701f4141eca9"}

As you can see, the IDs that define a step don't match the IDs needed to connect the steps through the workflow (the workflow starts with a step id=49, it's next step is referenced as id=1 but the next step is defined as id=50)

- Tiles with missing avatar: all tiles seem to be with no avatar since the url is null for all of them

![avatar](https://cloud.githubusercontent.com/assets/17053960/13129088/ecddea96-d5b0-11e5-89f5-78e527ca2da4.PNG)
![avatarnull](https://cloud.githubusercontent.com/assets/17053960/13129092/f15b99d8-d5b0-11e5-8a8e-959f81334756.PNG)

**Comment by Miguelcldn** [comment]
I'm checking the manifest, @Fermat-ORG/fermat-org-sierra-team could someone check on the missing `avatar_url`?

**Comment by Miguelcldn** [comment]
```xml
<process platform="CCP" name="Refuse Payment Request from Intra user" description="A Wallet's Intra User refuse a payment request sent by another actor." previous="List Payment Request">
 <steps>
     <step id="0"
         type="start"
         title="Select payment request record to refuse "
         description="The actor selects a payment request from the list and press deny button."
         platform="CCP"
         superlayer=""
         layer="Reference Wallet"
         name="Bitcoin Wallet"
         >
         <next>
             <step id="1" type="direct call"></step>
         </next>
     </step>
     <step id="1"
         type="activity"
         title="Route request to payment request plugin"
         description="The module routes this payment request refuse to the Crypto Payment Request Plugin to reach the selected intra user."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Wallet Module"
         name="Crypto Wallet"
         >
         <next>
             <step id="2" type="direct call"></step>
         </next>
     </step>
     <step id="2"
         type="activity"
         title="Route refuse to network service"
         description="The module routes this refuse to the network service to reach the selected intra user."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Request"
         name="Crypto Payment Request"
         >
         <next>
             <step id="3" type="direct call"></step>
         </next>
     </step>
     <step id="3"
         type="activity"
         title="Call the intra user to deliver the refuse"
         description="The network service places a call to the intra user and then it delivers the refuse via the Fermat network."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Network Service"
         name="Crypto Payment Request"
         >
         <next>
             <step id="4" type="direct call"></step>
         </next>
     </step>
     <step id="4"
         type="communication"
         title="Transport request"
         description="The payment request is transported through the communication layer and one of the available channels."
         platform=""
         superlayer="P2P"
         layer="communication"
         name="Communication Layer"
         >
         <next>
             <step id="5" type="fermat message"></step>
         </next>
     </step>
     <step id="5"
         type="activity"
         title="Receive the payment request"
         description="The network service receives the refuse and informs that to Request Crypto Payment Plugin."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Network Service"
         name="Crypto Payment Request"
         >
         <next>
             <step id="6" type="event"></step>
         </next>
     </step>
     <step id="6"
         type="activity"
         title="Update the request status"
         description="The payment request is update with the status deny."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Request"
         name="Crypto Payment"
         >
         <next>
             <step id="7" type="direct call"></step>
         </next>
     </step>
     <step id="7"
         type="activity"
         title="Return payment request send list"
         description="The module returns the payement request send list."
         platform="CCP"
         superlayer=""
         component="Plugin"
         layer="Wallet Module"
         name="Crypto Wallet"
         >
         <next>
             <step id="8" type="direct call"></step>
         </next>
     </step>
     <step id="8"
         type="end"
         title="List Send Payment Request"
         description="The wallet's user go to Payment Request menu and list payment request send, and show this status."
         platform="CCP"
         superlayer=""
         layer="Reference Wallet"
         name="Bitcoin Wallet"
         >
 
     </step>
 
 </steps>
 </process>
```

This is the xml extract. It looks like it's a server issue. I'm assigning @fuelusumar until he assigns someone to fix it

**Comment by campol** [comment]
Al parecer la causa del problema es que no se estan borrando los procesos y como consecuencia; no se borran los steps, los componentes, los layers, super layers y los platfrms. Ya que si se ejecutara todas las funciones de borrado, se ejecutaria la funcion loopPlatfrms(0); que es la que se encarga de guardar todo en la base de datos.

Para darme cuenta de este error primero aplique debug a la funcion parserManifest y me di cuenta que funciona perfectamente, luego aplique debug a la funcion saveManifest que opera sobre los datos que devuelve la funcion parserManifest, chequie la variable _procs y sus datos son correctos, entonces escribi mensajes de alerta en el log antes de cada definicion de las funciones loop (ej. var loopLays = function (u) ) y dentro de cada funcion tambien escribi mensajes en el log para darme cuenta si se entraba en la funcion. Las funciones loop se llaman en la funcion loopPlatfrms(0) la cual se llama despues del borrado de los procesos, layers, superlayers etc.

// deleting previous database
console.log("deleting previous database");
procMod.delAllProcs(function (err_del, res_del) {
winston.log('info', 'deleting proccess...');
	if (err_del) {
 	     winston.log('error', err_del.message, err_del);
	}
	compMod.delAllComps(function (err_del, res_del) {
		winston.log('info', 'deleting components...');
		if (err_del) {
			winston.log('error', err_del.message, err_del);
		}
		layerMod.delAllLayers(function (err_del, res_del) {
		winston.log('info', 'deleting layers...');
			if (err_del) {
			     winston.log('error', err_del.message, err_del);
			}
			suprlayMod.delAllSuprlays(function (err_del, res_del) {
				winston.log('info', 'deleting superlayers...');
				if (err_del) {
					winston.log('error', err_del.message, err_del);
				}
				platfrmMod.delAllPlatfrms(function (err_del, res_del) {
					winston.log('info', 'deleting platforms...');
					if (err_del) {
						winston.log('error', err_del.message, err_del);
					}
			        	console.log("define loopPlatfrms(0)");
					return loopPlatfrms(0);
				});
			});
		});
	});
});

Esta funcion procMod.delAllProcs no esta borrando los procesos el origen esta aca /modules/repository/process/services/proc.js

exports.delAllProcs = function (callback) {
    'use strict';
    procDao.delAllSchemas(function (err, comp) {
        callback(err, comp);
    });
};

Por alguna razon este código no esta haciendo su trabajo.
