### ISSUE TITLE
Let space for GUI components

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#445]
As I understand to @Luis-Fernando-Molina claim, the components above the _module_ layer must have more space between layers.

**Comment by Luis-Fernando-Molina** [comment]
No es mas espacio entre layers, sino separar la interfaz grafica del resto de los plugins por un espacio en blanco horizontal

**Comment by IsaTab** [comment]
Before

![before](https://cloud.githubusercontent.com/assets/17053960/13156330/6047ce28-d658-11e5-9a7f-8fa912a70a17.PNG)

After

![after](https://cloud.githubusercontent.com/assets/17053960/13156337/66a5daa8-d658-11e5-859b-03b224547970.PNG)

**Comment by Miguelcldn** [comment]
Is that right? @Luis-Fernando-Molina
