### ISSUE TITLE
Fix the Stack view

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#447]
![stack](https://cloud.githubusercontent.com/assets/5544266/13157253/fce000ac-d658-11e5-9867-11356bc091f4.png)

Since the "stack" view was developed, a lot of platforms and super layers were added, and some without any dependencies, generating what we see here. The task is to correctly draw the stack view and set them further away from the camera in order to see all the groups headers at the simple view

**Comment by IsaTab** [comment]
![stack](https://cloud.githubusercontent.com/assets/17053960/13161494/7e24b3cc-d674-11e5-9c7e-705e0a59849b.PNG)
