### ISSUE TITLE
Crear función para utilizar fermat-edit sin iniciar sesión.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#451]
Necesario para #377.

**Comment by Miguelcldn** [comment]
Este cambio sigue existiendo? Debe eliminarse, bajo ninguna circunstancia se puede editar el manifiesto sin iniciar sesión. Si es para prueba basta con iniciar sesión quien sea que esté probando una vez y el navegador lo recordará

**Comment by ricardo460** [comment]
esta opción solo estará disponible para el puerto 8081 que dirige a la BD de prueba, de lo contrario no se activara.
