### ISSUE TITLE
Se requiere el poder eliminar, insertar, editar en workFlowEdit.js

### ISSUE THREAD

**Issue by emmanuelcolina** [Fermat-ORG/fermat-org#454]
Se necesita agregar diversas funciones para workFlowEdit, las cuales son insertar, editar y eliminar workflow.

Tareas a realizar:

- [x]  Creación de nuevo workflow:
  - [x] Crear un nuevo plano para el nuevo workflow.
  - [x]  Posicionar plano.
  - [x] Dibujar plano con su respectiva configuración inicial.
  - [x] Añadir todas la Edición del workflow.

- [x] Edición de un workflow:
  - [x] Llenar campos con su configuración actual.
  - [x] Editar plano con su nueva configuración.
  - [x] Posicionar plano en su posición final.
  - [x] Guardar configuración.

- [x] Eliminación de un workflow.
  - [x] Borrar plano(Objeto) y modificar variable donde se guarda.
  - [x] Configurar animación de los workflow que quedaron.

Necesario para #467.

**Comment by Miguelcldn** [comment]
Next: #460

**Comment by emmanuelcolina** [comment]
- [x] Dibujado de la estructura del arbol(workflow) dinamicamente en tiempo real
- [x] Creacion de nueva estructura en worflowedit
- [x] Modificacion del archivos actionManager.js 
- [x] Modificacion del archivos actionFlow.js 
- [x] Insertar elemento en la vista workflow dinamicamente
      - [ ] Bug encontrado

**Comment by Miguelcldn** [comment]
Mucho trabajo para una sola persona, no se puede separar y agilizar el desarrollo?

**Comment by ricardo460** [comment]
pues si, de aquí van ha salir varios issues haciendo referencia a este. con su respectivo desarrollador.

**Comment by ricardo460** [comment]
applied changes
