### ISSUE TITLE
Texto de ayuda para los nuevos visitantes

### ISSUE THREAD

**Issue by gustl-arg** [Fermat-ORG/fermat-org#455]
@Miguelcldn estamos teniendo repetidas consultas de los participantes de la Dubai Competition ( a traves del competition manager @rjgroenke que no saben que hacer cuando ingresan al sitio...
podriamos incluir algunas indicaciones para orientar al usuario ?

[] cartel de bienvenida que indique que hay que esperar q que se cargue toda la prezi
[] indicacion para hacer clic sobre las flechas azules
[] indicacion de como navegar con drag para mover lienzo y con scroll para zoom
[] otras ??

Gracias!

**Comment by Miguelcldn** [comment]
Listo, @IsaTab se encargará de esto. Isaías, esto tiene carácter de urgencia, y los textos de ayuda (en inglés) no deben afectar la interacción de aquellos que ya saben usar la página.

**Comment by gustl-arg** [comment]
@IsaTab podes pasarle una version draft a nuestro traductor @daveo90 antes de subirlo, si preferís..
seguramente yo tambien te de feedback una vez que los vea colocados..

**Comment by IsaTab** [comment]
@gustl-arg @Miguelcldn @daveo90

Cartel de bienvenida: Desaparece al cargar completamente la página.
![welcome](https://cloud.githubusercontent.com/assets/17053960/13308968/b4d21f7a-db4e-11e5-969c-eede889f1d44.PNG)

Ayuda para el usuario: Aparece tras un tiempo determinado durante el cual el usuario ha permanecido en la vista principal tras haber cargado la página. La ayuda desaparece tras abandonar la vista principal.
![help](https://cloud.githubusercontent.com/assets/17053960/13309014/30c1072c-db4f-11e5-9c03-da3abcd39b46.PNG)

**Comment by Miguelcldn** [comment]
Falta el _Left click to pan after you zoom in_ y _Press Esc in any view to go back to its starting position_

**Comment by Miguelcldn** [comment]
Tambien quita el "fermat-org", podeis poner solo "Welcome!...."

**Comment by daveo90** [comment]
![image](https://cloud.githubusercontent.com/assets/15698060/13323693/bd112cea-dbac-11e5-95e5-01e3b2e2dce9.png)

**Comment by gustl-arg** [comment]
excelente trabajo y ayuda a los nuevos! gracias! @Miguelcldn @IsaTab @daveo90 cuando entra en funcionamiento ?

**Comment by Miguelcldn** [comment]
Ya está en línea en dev.fermat.org :+1:
