### ISSUE TITLE
Delete the "Show workflow" button in the Table view

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#459]
In Navi v1.0 we used to show the workflow of a component by clicking on a component and then the sign "Loading workflow..." was shown while the client got the data, then it changed to "Show workflow". But that's not needed anymore as in Navi v2.0 there is a dedicated view for showing all workflows.

*Note:* Only delete the button and loading message, as @emmanuelcolina and @ricardo460 are changin the way workflows works, there will be conflicts if you change anything in the flowManager or actionFlow class.

**Comment by Miguelcldn** [comment]
Next: #460

**Comment by Miguelcldn** [comment]
Is this done? @IsaTab

**Comment by IsaTab** [comment]
Yes, I forgot to reference it: commit 40758448d67c2b24af71bcbb66acd5c167dcd953 @Miguelcldn

**Comment by Miguelcldn** [comment]
Ok, done then
