### ISSUE TITLE
Rename actionFlow for workflow and flowManager for workflowManager

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#461]
Aprovechando que están trabajando con los workflows, renombren el archivo y clase actionFlow para que sea workflow, igualmente flowManager renombrar por workflowManager.

Puesto que esto es un refactory, este issue es delicado y debería realizarse en sincronización y un fin de semana, de manera que todo se mezcle antes del cambio y no haya conflictos.

(Te asigno el issue @emmanuelcolina para que luego con @ricardo460 decidan quién lo va a hacer, reasignas a quien lo vaya a hacer)

**Comment by emmanuelcolina** [comment]
Ok @Miguelcldn, tambien hay que reombrar fermatEdit.js por tableEdit.js y dejar funciones que se estan reutilizando actualmente en fermatEdit como un unico archivo independiente(helper.js), ya que ahora existira workFlowEdit.js, esto ya lo discuti con @ricardo460
