### ISSUE TITLE
Developers view

### ISSUE THREAD

**Issue by IsaTab** [Fermat-ORG/fermat-org#464]
In this view a tile must be clicked to fully show a developer's information; however, the range given to this action (clicking on any tile) extends beyond a single tile and partially overlaps with another tile showing the information of a developer that wasn't clicked.
![developers](https://cloud.githubusercontent.com/assets/17053960/13374198/c49704dc-dd53-11e5-83d8-8df6bf64bc3a.PNG)
The red framed box indicates the click area where the tile on the top left is shown.

**Comment by Miguelcldn** [comment]
So it was a real issue after all, that happened to me once but I thought it was my pc
