### ISSUE TITLE
Some users can't login

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#471]
![loginerror](https://cloud.githubusercontent.com/assets/5544266/13448490/ece40f44-dff5-11e5-81d2-88eb4bf15894.PNG)

Este es el error que ocurre al loguear

**Comment by Miguelcldn** [comment]
Creo que tiene que ver más bien con @Fermat-ORG/fermat-org-sierra-team :s @fuelusumar

**Comment by fuelusumar** [comment]
ya se lo voy a asignar a @campol, el problema es que está tratando de guardar tu usuario, pero este ya existe, por eso da ese error de duplicidad
