### ISSUE TITLE
create new designs for fields workFlowEdit.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#472]
Se necesita crear un diseño cómodo en los campos para el manejo de workFlowEdit.

primera vista:

![workflow-modal](https://cloud.githubusercontent.com/assets/13169767/13448863/827afb24-dff8-11e5-9493-6ba4e3ab6745.png)

Necesario para #467.

**Comment by emmanuelcolina** [comment]
Campos:
- Header: 
     * Title
     * Description 
     * Plataform
- Steps(Hijos): 
     * Title
     * Description
     * type
     * Steps
         * ID(a que paso va vinculado)
         * Type Call: (tipo de llamada)
     * Name: (Nombre del componente)
     * Layer: (Layer del componente)
     * Plataform: (Plataform de un componente)

**Comment by ricardo460** [comment]
new design applied
