### ISSUE TITLE
Create animations for actions for workFlowEdit.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#484]
Crear las animaciones para la entrada de un nuevo workFlow, entrada y salida de un workFlow que esta siendo modificado y salida de un workFlow que esta siendo eliminado.

Necesario para #454 y #467.

**Comment by emmanuelcolina** [comment]
- [x] Insert
- [x] Delete
- [ ] Modify

**Comment by ricardo460** [comment]
applied changes
