### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#488]
**Create:**
- [x] TKY (Tokenly Platform). Right to MKT.
- [x] Song Wallet (layer). Over Wallet.
- [x] External Api (layer). Below Network Service

**Move:**
- [x] WRD - World Api - Tokenly --> TKY - External Api - Tokenly

**Delete:**
- [x] WRD (Platform)
- [x] World (Super layer)

Requested by @darkestpriest

**Comment by Luis-Fernando-Molina** [comment]
La plataforma de Tokenly debe llamarse TKY

Lo de World layer entiendo que no va a ser necesario.

**Comment by Miguelcldn** [comment]
@Luis-Fernando-Molina si el layer World no se va a crear, entonces donde quedará el plugin **Tokenly** actualmente en *WRD - World Api*?

**Comment by darkestpriest** [comment]
@Miguelcldn La super capa world no va, el plugin Tokenly lo tenemos identificado en la nueva capa llamada external API

**Comment by darkestpriest** [comment]
Issue updated

**Comment by Miguelcldn** [comment]
@darkestpriest already done
