### ISSUE TITLE
"There is already a component with that name in this group and layer, please use another one" message when I try to edit the plugin authors

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat-org#489]
Cuando intento modificar el autor de un plugin ya creado anteriomente desde el manifest, sigo los pasos correspondiente para realizar la asignación del autor, todo bien hasta allí, pero, al momento de hacer click en el botón "save" se produce un error en el sitio indicando **There is already a component with that name in this group and layer, please use another one**, siendo este el único plugin de su tipo en todo fermat. Luego de ese error, salgo de la pantalla de edición y al revisar el componente, sigue el autor anterior.

**Comment by ricardo460** [comment]
@darkestpriest problema resuelto, cambios aplicados.

**Comment by darkestpriest** [comment]
Hola, @ricardo460, el problema se mantiene si luego de asignar el autor presiono el botón "save", pero, he notado que si hago click fuera del componente antes de hacer click en el botón "save" si se actualiza el componente.

**Comment by Miguelcldn** [comment]
@ricardo460 el error que describe @darkestpriest sigue presente? para reabrir el issue

**Comment by ricardo460** [comment]
@Miguelcldn no, error resuelto.
