### ISSUE TITLE
Upload the missing headers and logos

### ISSUE THREAD

**Issue by IsaTab** [Fermat-ORG/fermat-org#490]
Currently, the image for a header seems to be missing:

- Architecture view:
![missing header](https://cloud.githubusercontent.com/assets/17053960/13703747/7cdb5920-e76e-11e5-84ac-ffad0539128a.png)

- Workflows view:
![workflows - missing header](https://cloud.githubusercontent.com/assets/17053960/13703756/8dc6161c-e76e-11e5-9e08-04845077bf4e.PNG)

And there's also a bug with the positioning of a header:

- Architecture view:
![header bug](https://cloud.githubusercontent.com/assets/17053960/13703768/a530bd02-e76e-11e5-8598-d787cfa4ab23.png)

- Workflows view:
![workflows - header bug](https://cloud.githubusercontent.com/assets/17053960/13703785/b76dc168-e76e-11e5-987d-85c6026ab01b.PNG)

**Comment by simonorono** [comment]
![missing](https://cloud.githubusercontent.com/assets/12176276/13710836/9191cf92-e78d-11e5-9462-1e412f0875e6.png)
![screenshot at 2016-03-11 13 06 33](https://cloud.githubusercontent.com/assets/12176276/13710835/91872c86-e78d-11e5-8174-93a3bf9d97af.png)

Confirmado

**Comment by Miguelcldn** [comment]
That's a normal behavior, that's because Fermat people creates Groups before the logos get ready

**Comment by simonorono** [comment]
Still missing the ART icons.
