### ISSUE TITLE
Not to draw some tile details if camera is far away

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#497]
At commit 9e496d4534bc5eccc407da3629891dc331d385ef I added in the config_tile.json file a enum of qualities with a value for each one.

In the same file, some of the elements should have a property `minQuality : [0-3]` which will represent what is the minimal quality for the element to be rendered. In the tileManager code, when that file is being read to create the texture, if the _level_ of the parameter is lower than the _minQuality_ of an element, add to the _data_ the property `skip : true`. And the drawPicture and drawText should check if the _skip_ property of the actual element is set to true to skip that element, if set to false or not set at all then draw it.

**Comment by simonorono** [comment]
> some of the elements

Which ones?

> should have a property `minQuality : [0-3]`

What's the criteria to select this? If you already have this defined, send it over, please

**Comment by Miguelcldn** [comment]
> Which ones?
You decide, what can you descry at certain distance?

> What's the criteria to select this?
Depending of the above, you are going to decide which `minQuality` an element will have.

The qualities of the tile and its minimal distance is defined in `tileManager.js:505`.

For example: if `camera.position.z = 1500` (medium quality) and you can see clearly the Tile Code but you can't distinguish the Layer Name then the Layer Name's *minQuality* should be *high* as you can't see it in the medium quality. While the Tile Code's *minQuality* could be *medium* or lower if it can be seen even further.

In the json file, *minQuality* will be `[mini | small | medium | high]` and in the code, you will map them in the same file against the `qualities` section of the json, in order to get a numerical value and be able to compare. So *small* < *medium* because *small = 1* & *medium = 2* for example.
