### ISSUE TITLE
Compile the list of users who will have access to the TSE functionality

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#506]
Here should be the list of the users who will have access to this functionality

**Comment by nelsonalfo** [comment]
Hi! I can Edit/Create/Delete platforms, layers and super layers

**Comment by darkestpriest** [comment]
HI, in the near future I'll need to add new platforms and, probably, new layers.

**Comment by Rart3001** [comment]
hello, me too

**Comment by Rart3001** [comment]
hello, me too

**Comment by lnacosta** [comment]
@furszy @acostarodrigo and I will probably administrate too this kind of things.
