### ISSUE TITLE
If you change a tile's name for another existent one, it will accept it

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#511]
Steps to recreate the error:

- Login in dev.fermat.org
- Create a tile with name Test
    - Update and re-login if you want
- Create a tile in the same place and type and name Test Two
- Rename the Test Two tile to Test (it's expected to get an error message, but the API accepts it)

**Comment by fuelusumar** [comment]
Ready! now it wont let put 2 components with the same name in the same layer. The problem was the platform and the superlayer, for some reason when one of them is null, the database index takes them as distincts.
Now the index evaluates layer_id, name, given that none of them can or should be null
