### ISSUE TITLE
Implement permissions to modify the Table Structure

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#515]
As the TSE (see the milestone with that name) is a functionality that not everybody will have access to, we should keep the permissions of every developer in order to check if they can edit the structure or not. Such field will be in every developer and its name should be `canEditStructure` which is boolean and optional while its default value will be `false`.

Needed for #516 and #517.

**Comment by Miguelcldn** [comment]
@campol: The structure of the permissions will not be as described in the description of this issue, we have designed another way of permission system based on the *nix permission system a set of octal digits which means any combination of add, edit, remove. For example, if the permission is 6 that means that someone has permission is 110 in binary, and that means the user can add and edit but not remove. The permissions actually are about platform, superlayer and layer respectively, so the perms will be a 3-digit octal number.

Users will have by default the next permissions:
```
667 = 110 110 111 -> (add|edit platforms), (add|edit superlayers), (add|edit|remove) layers)
```

For related code to how to check permissions see https://gist.github.com/simonorono/ea02997c40932cb3e1b49b2a70637f45

**Comment by simonorono** [comment]
**Update**: By default, user permissions will be `77000`

**Comment by campol** [comment]
I do not understand what it means 77000?
@fuelusumar

**Comment by simonorono** [comment]
**Additional**

The highest integer in JS (given by the constant `Number.MAX_SAFE_INTEGER`) is `9007199254740991`, which is *storable* in a 64-bit integer (a.k.a. `long`).

With such field in the database, we will have the ability to scale if more permissions are needed in the future, giving us 16 possible permissions (`9007199254740991` is 16 digit long and is higher than `7777777777777777`)

I would like your comments and ideas @campol @fuelusumar #sierra

**Comment by simonorono** [comment]
@campol 

Each digit of the number needed for permissions represents an octal value, this is, an integer 3-bit long.

Each one of these bits represents the ability to add, edit, or delete an element.
@Miguelcldn's example:
```
667 = 110 110 111 -> (add|edit platforms), (add|edit superlayers), (add|edit|remove) layers)
```

Where @Miguelcldn's example is slightly mistaken is in the order of the permissions, as of right now, we handle this order:

```
Components | Workflows | Platforms | Superlayers | Layer
```

Refer to [this](https://gist.github.com/simonorono/ea02997c40932cb3e1b49b2a70637f45) example code to see how to query/set permissions from/to this integer.
