### ISSUE TITLE
Create a route or mechanism so a user can give permissions to another

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#517]
It's planned that in TSE functionality, a user (obviously with the right permission) could give the same permission to another one giving its github username.

For example: *MiguelCldn* enters TSE, and wants *fuelusumar* to have the permissions to enter and edit, *MiguelCldn* sends the API the route to give permission and provides the *fuelusumar* username (via a form). The API server should re-check first *MiguelCldn*'s permission (for security reasons) and if successful, give *fuelusumar* the permission.

For audit reasons, we should know who invited who.

**Comment by campol** [comment]
#515
