### ISSUE TITLE
Add the new Header PTH

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#519]
It's available here https://github.com/jhonmarquez92/fermat-graphic-design/commit/94dcf503fad896cb4788ee0a7d88a7162a7e8c15

**Comment by simonorono** [comment]
That URL returns 404

**Comment by Miguelcldn** [comment]
I supposed it, you have no access to graphic design repo T_T

**Comment by Miguelcldn** [comment]
All logos updated
