### ISSUE TITLE
When adding platform, order and logo should be optional

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#527]
http://api.fermat.org/#api-Repo_Platform-AddPlatform

If no order is provided, "Invalid or missing data" is sent. It should add to the end if the order is not provided.

The logo should not even exist, because the logo is always [code]_logo.png.

Check this in other queries

**Comment by Miguelcldn** [comment]
I added a new platform without adding the `order` field, the result was that the new platform became `order=0` and thus being positioned before *COR*. It was expected that the new platform be added **at the end**, not at the beginning.

**Comment by campol** [comment]
@Miguelcldn the same applies to layer and superlayer?

**Comment by Miguelcldn** [comment]
Yes
