### ISSUE TITLE
Some workflow steps are has not shown the related tile

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#537]
Every step should have a tile related

**Comment by kyxer** [comment]
can you please reference url example, what do you expect in response url?

**Comment by Miguelcldn** [comment]
When the client asks for the workflows it receives the json, where the steps have this structure:

```json
{
	"_id": "56e1e2718fb3968867d2a337",
	"id": 2,
	"title": "Asset User Identity",
	"desc": "Asset User Identity is created and User Actor is registered in P2P",
	"type": "activity",
	"next": [{
		"id": "3",
		"type": "direct call"
	}],
	"name": "asset user",
	"layer": "identity",
	"platfrm": "DAP"
}
```

But, in some steps there are no tile related to it

```json
{
	"_id": "56e1e2718fb3968867d2a331",
	"id": 1,
	"title": "Asset User Wallet",
	"desc": "Starts by opening the Asset User Wallet with positive balance of an asset",
	"type": "activity",
	"next": [{
		"id": "2",
		"type": "direct call"
	}, {
		"id": "3",
		"type": "direct call"
	}]
}
```

One of those reported workflows is the following:

![workflows](https://cloud.githubusercontent.com/assets/5544266/14397229/fa684216-fda5-11e5-9048-b1f4e4b6538f.png)

Where in the manifest (when in lab there was being read from the development branch) it was written:

![manifest](https://cloud.githubusercontent.com/assets/5544266/14397255/1eed8650-fda6-11e5-8d50-3eb648bd03f4.png)


(I don't know if it's still the case for this particular workflow)
