### ISSUE TITLE
Steps without father

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#538]
In `workflow` view, when the user clicks a header, all the related workflows are expanded, but some of them has steps drawn without father and we can see something like this

![pasted image at 2016_04_07 10_00 pm](https://cloud.githubusercontent.com/assets/5544266/14390753/6c6621fe-fd82-11e5-9f50-ba316d416a92.png)

Reported by @acostarodrigo

**Comment by simonorono** [comment]
![2016-04-11-114219_1360x768_scrot](https://cloud.githubusercontent.com/assets/12176276/14434003/8620d558-ffda-11e5-80dc-c2bf7949a565.png)
![2016-04-11-114106_1360x768_scrot](https://cloud.githubusercontent.com/assets/12176276/14434016/8cd2186c-ffda-11e5-9d04-cf8261130661.png)

Esos dos nodos que aparecen allí "aislados" están marcados como iniciales (`type: "start"`)
