### ISSUE TITLE
Create group icon and logo from svg

### ISSUE THREAD

**Issue by IsaTab** [Fermat-ORG/fermat-org#559]
After a group's logo (icon) is approved a designer must upload it to the TSE in order to create said group; the designer uploads two SVGs: one for the group header logo and the other for said group's tiles. The SVGs must be converted into a series of PNGs and be upload to their respective folders.

**Comment by fuelusumar** [comment]
@IsaTab can you add a comment with the png's resolutions or sizes and the types, @Miguelcldn talked about to types of svg (icon and header). Talk about that here, so we have it documented, thanks

**Comment by IsaTab** [comment]
"C:\fermat-org\clair\images\tiles\icons\group\svg"
high--dpi=720
medium--dpi=90
small--dpi=45
mini--dpi=22

"C:\fermat-org\clair\images\tiles\icons\type\svg"
high--dpi=720
medium--dpi=90
small--dpi=45
mini--dpi=22

"C:\fermat-org\clair\images\headers\svg"
high--dpi=360
medium--dpi=90
small--dpi=45

Sorry for the wait, hadn't check the issues today.
