### ISSUE TITLE
User permission verification

### ISSUE THREAD

**Issue by IsaTab** [Fermat-ORG/fermat-org#597]
While using the server's api route for this verification, some of the data retrieved for certain users comes undefined.

![permissions retrieval](https://cloud.githubusercontent.com/assets/17053960/15332730/d02bae68-1c34-11e6-94ee-445ec4954ddd.png)

Using the URL route in a browser or a REST client displays the data properly, however this happens when retrieving using AJAX on the client side.

**Comment by Miguelcldn** [comment]
Did you print the raw response in the browser's console? I suspect the json could have a bad syntax error or something

**Comment by IsaTab** [comment]
The data that was retrieved properly has the raw response included as [object Object], in the case with the undefined data the respones is there but is a blank since there's nothing.

**Comment by Miguelcldn** [comment]
Check you user_id's permissions for both REST client and browser, are those the same? maybe a permission issue?

**Comment by simonorono** [comment]
Why would it give a result for **some** of the users then?

**Comment by campol** [comment]
no todos los usuarios tienen permiso asignado, los que faltan por permisos hay que introducircelos, para eso hay una ruta

**Comment by campol** [comment]
http://api.fermat.org/#api-User-ChangePermission

**Comment by IsaTab** [comment]
The issue turned out to be the databases, I had assumed that both production and development database would have permissions set for all the users registered.
