### ISSUE TITLE
If a group is renamed, rename its dependencies

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#609]
if a platform "WPD" is renamed to "APD", the server should look in all plaftorms/super layers dependencies in order to rename all "WPD" dependencies to "APD"

**Comment by campol** [comment]
@Miguelcldn: this also applies to super-layers? for example if you rename a super layer I have to update all platform and super layers having it as dependency

**Comment by Miguelcldn** [comment]
Yes, as described in the title and text. Even if a platform or super-layer is modified, it must search all platform *and* super-layers to check dependencies.

**Comment by Miguelcldn** [comment]
It's better if you save the dependencies with the ID of the object, and when there's a request, change the id for the code and name.

For example:
If _COR_ depends on _P2P_ then in the database it should be:
```
COR : {
   deps: ["AFDE19162584"] //P2P's ID, instead of "P2P"
}
```

And when the route is requested, just change it for its name:
```
COR : {
   deps: ["P2P"]
}
```

In that way, the name can be changed whenever they want, and there will be always correct. Of course, if the client requests to apply a dependence, you should ask the name ("P2P") and save the ID. And when a group is deleted, you should delete all dependencies linking to that ID.

**Comment by campol** [comment]
@simonorono, @IsaTab: you can store the code instead of dependence on id?
for example:
instead of this
deps = APD, CORE, TXI
this
deps = "576426420c327dad128f797f", "576426420c327dad128f798f", "576426420c327dad128f799f"

**Comment by campol** [comment]
@Miguelcldn: what will happen with the dependencies that are stored with the code?
must be changed by ids, for that I need help
