### ISSUE TITLE
Choose a theme for the blockchain explorer

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#620]
**Cerulean**
![cerulean](https://cloud.githubusercontent.com/assets/5544266/15943026/0589d5da-2e55-11e6-887e-dff9b7a3f449.PNG)

**Lumen**
![lumen](https://cloud.githubusercontent.com/assets/5544266/15943029/05988544-2e55-11e6-940c-62035623ddc2.PNG)

**Paper**
![paper](https://cloud.githubusercontent.com/assets/5544266/15943034/05f2ccc0-2e55-11e6-9b31-235604fdb889.PNG)

**Readable**
![readable](https://cloud.githubusercontent.com/assets/5544266/15943027/058f9b8c-2e55-11e6-821b-816cbcabc053.PNG)

**Sandstone**
![sandstone](https://cloud.githubusercontent.com/assets/5544266/15943028/05981c94-2e55-11e6-8884-6cfcd77ed47e.PNG)

**Simplex**
![simplex](https://cloud.githubusercontent.com/assets/5544266/15943030/059cca28-2e55-11e6-8f04-4b536d6c9b5f.PNG)

**Spacelab**
![spacelab](https://cloud.githubusercontent.com/assets/5544266/15943031/05ae7cdc-2e55-11e6-8319-e7a2bdf2feb8.PNG)

**United**
![united](https://cloud.githubusercontent.com/assets/5544266/15943032/05b18c38-2e55-11e6-8eca-bde5517099d4.PNG)

**Yeti**
![yeti](https://cloud.githubusercontent.com/assets/5544266/15943033/05bc7dd2-2e55-11e6-88b9-34a8e59e6c6f.PNG)

Please choose one of them @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
United

**Comment by Miguelcldn** [comment]
Thanks
