### ISSUE TITLE
No response on PUT request

### ISSUE THREAD

**Issue by simonorono** [Fermat-ORG/fermat-org#624]
Whenever I try to edit a platform that doesn't not exist server gives no answer. 

Test call (platform must not exist):
`
curl -XPUT -d "platform_id=575ddf14cc328a842c009533" -d "code=SIM" -d "name=Simon" -d "logo=mon" -d "order=87" "http://127.0.0.1:8002/v1/repo/usrs/56f19f0a301492726c80881a/platfrms/575ddf14cc328a842c009533?env=development&axs_key=570e44e3019d61dc4de9f32f"
`

**Comment by Miguelcldn** [comment]
Please, make your tests in `env=testing`. The SIM platform were created and it's visible in dev.bitdubai.com

**Comment by simonorono** [comment]
@Miguelcldn the URL is local O.o

**Comment by Miguelcldn** [comment]
Well, I don't know but I saw SIM platform in the development DB, I erased it
