### ISSUE TITLE
Create ADD (Fermat Addons) SuperLayer

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#631]
This super-layer will be enclosing all layers between OSA and BCH (basically, all addons). This should be done after the logo is created, that issue will be referenced here.

It's design is in Fermat-ORG/fermat-graphic-design/issues/937

**Comment by Miguelcldn** [comment]
![image](https://cloud.githubusercontent.com/assets/5544266/16779289/989e6b0c-483f-11e6-8a9e-a3eec551eb1b.png)

**Comment by campol** [comment]
Hello @emmysm how are you today?
I need you to please change the dimensions of the logo svg Fermat ADD to 1732 x 579 pixels, and it does not look good.

**Comment by emmysm** [comment]
Sure. I will do :)
