### ISSUE TITLE
Add the letters limit to the description and title of the steps.

### ISSUE THREAD

**Issue by ricardo460** [Fermat-ORG/fermat-org#677]
![captura de pantalla 59](https://cloud.githubusercontent.com/assets/13169767/16810752/3246a4e6-48f3-11e6-8812-bb508851e94c.png)

required for #568

**Comment by ricardo460** [comment]
No esta cubriendo todo el espacio disponible.

* Aumentar limite y realizar pruebas.
 
![captura de pantalla 66](https://cloud.githubusercontent.com/assets/13169767/16826600/ad6318ae-494c-11e6-8e49-90eb88935e02.png)

**Comment by emmanuelcolina** [comment]
Ok, entonces el testeo no lo hacemos con letras mayusculas.
