### ISSUE TITLE
Create the caller function in the client side

### ISSUE THREAD

**Issue by Miguelcldn** [Fermat-ORG/fermat-org#703]
A function that resembles the `assert` function in some languages, a static function that when called with a condition, if this condition is false, must prepare a message to send to the API in order for it to create an issue. The way that the function will collect the call-stack, variables and current line is up to you.

**Comment by simonorono** [comment]
There are some issues with the requirements:

1. The line number will be present on the call stack (the only way I've found it can be done); that's ok, but it will report the line number of **the file generated by `gulp`**.
2. There's no a way to programmatically get all variables in the current scope, **only** all variables in the `window` object or the `this` object, both resulting in a slow operation and a big result.

**Comment by Miguelcldn** [comment]
1. That's exactly what we want, if main.js changes the bug's line, then that means that in the "new" version, the error persists.

2. This can be done using `this` passed as a parameter to the function, such function can iterate over `this` to take the variables excluding functions and filtering with `hasOwnProperty`. We would just need context variables so we don't need all them (luckily).
